EPTALIGHTS-CODE-EXTRACTOR-PHP-PATH=/path/to/eptalights-code-extractor-php

extract:
	make -C $(EPTALIGHTS-CODE-EXTRACTOR-PHP-PATH) extract-all-using-docker \
		src-rootpath="$(PWD)/src" dst-rootpath="$(PWD)/eptalights_code_extract_output_php"
